Repository duecredit/duecredit, pull requests merged in 2023-11, with the labels that each got.

#187 Move from Travis to github workflow, disable coveralls
  .github/workflows/test.yml
  .travis.yml
  duecredit/tests/test_api.py
  duecredit/tests/test_injections.py
  duecredit/tests/test_io.py
  setup.py
  tox.ini
Labels: tests

#186 RF: remove remaining usage of SIX, and thus move away fully from Python 2
  duecredit/cmdline/helpers.py
  duecredit/collector.py
  duecredit/dueswitch.py
  duecredit/entries.py
  duecredit/injections/injector.py
  duecredit/io.py
  duecredit/log.py
  duecredit/parsers.py
  duecredit/stub.py
  duecredit/tests/mod/imported.py
  duecredit/tests/mod/submod.py
  duecredit/tests/test__main__.py
  duecredit/tests/test_api.py
  duecredit/tests/test_cmdline.py
  duecredit/tests/test_collector.py
  duecredit/tests/test_entries.py
  duecredit/tests/test_injections.py
  duecredit/tests/test_io.py
  duecredit/tests/test_utils.py
  duecredit/tests/test_versions.py
  duecredit/utils.py
  duecredit/versions.py
  setup.py
Labels: release, internal

#192 Add some more `cite()` information to the README.md
  README.md
Labels: documentation

#206 raise, do not return some NotImplemented if type is other than what we can compare
  duecredit/entries.py
Labels: patch
